### PR TITLE
fix: configure css-loader to use modules

### PR DESCRIPTION
**Pull request by eckdanny-osi**
Handle `*.module.css` imports with `css-loader` configured for css modules.

### Issue:

\@cwds/components uses BS4 and `cognito-custom-login` side-loads BS3.3.7 from a cdn. This creates a collision (e.g.; `btn btn-primary`).

### Resolution

css-modules are there to solve the problem. Collisions in the global namespace can be resolved by simply opting into cssModules in the css-loader as appropriate (e.g.; the `*.modules.css` assets that \@cwds/components provides.)

Other Digital Service teams using \@rails/webpacker stack do not need anything like this because their builds are pre-configured with support for `*.module.[s]css` support out of the box. Same for any CRA@next projects.

### Notes

this PR just includes a webpack config change for `dev`.

### CODE REVIEW

**Comment by eckdanny-osi** [comment]
Things play mostly OK together with cssModuels:

screen shot 2018-10-31 at 1 31 23 pm

There are definitely going to be some collisions b/n the \@cares/core/dist/styles.css (our themed BS4 reset) and BS3.3.7. Same as if one attempted to mix BS3 and BS4

**Comment by kelfink** [comment]
Is 
https://github.com/ca-cwds/cognito-custom-login/pull/83 still relevant?  Looks like this one overrides PR 83

**Comment by kelfink** [comment]
So if this only modifies the web pack config for dev, is there further work to fix this for prod, or is it a dev-only issue ?

**Comment by eckdanny-osi** [comment]
The team should fix for prod too. I only meant to give the gist how.

**Pull request merged**
